<?php

declare(strict_types=1);

namespace MulerTech\Database\Relational\Sql;

/**
 * Class InformationSchemaTables
 *
 * Enum representing all available tables in the MySQL information schema.
 *
 * @package MulerTech\Database\Relational\Sql
 * @author Sébastien Muler
 */
enum InformationSchemaTables: string
{
    case ADMINISTRABLE_ROLE_AUTHORIZATIONS = 'ADMINISTRABLE_ROLE_AUTHORIZATIONS';
    case APPLICABLE_ROLES = 'APPLICABLE_ROLES';
    case CHARACTER_SETS = 'CHARACTER_SETS';
    case CHECK_CONSTRAINTS = 'CHECK_CONSTRAINTS';
    case COLLATION_CHARACTER_SET_APPLICABILITY = 'COLLATION_CHARACTER_SET_APPLICABILITY';
    case COLLATIONS = 'COLLATIONS';
    case COLUMN_PRIVILEGES = 'COLUMN_PRIVILEGES';
    case COLUMN_STATISTICS = 'COLUMN_STATISTICS';
    case COLUMNS = 'COLUMNS';
    case COLUMNS_EXTENSIONS = 'COLUMNS_EXTENSIONS';
    case ENABLED_ROLES = 'ENABLED_ROLES';
    case ENGINES = 'ENGINES';
    case EVENTS = 'EVENTS';
    case FILES = 'FILES';
    case INNODB_BUFFER_PAGE = 'INNODB_BUFFER_PAGE';
    case INNODB_BUFFER_PAGE_LRU = 'INNODB_BUFFER_PAGE_LRU';
    case INNODB_BUFFER_POOL_STATS = 'INNODB_BUFFER_POOL_STATS';
    case INNODB_CACHED_INDEXES = 'INNODB_CACHED_INDEXES';
    case INNODB_CMP = 'INNODB_CMP';
    case INNODB_CMP_PER_INDEX = 'INNODB_CMP_PER_INDEX';
    case INNODB_CMP_PER_INDEX_RESET = 'INNODB_CMP_PER_INDEX_RESET';
    case INNODB_CMP_RESET = 'INNODB_CMP_RESET';
    case INNODB_CMPMEM = 'INNODB_CMPMEM';
    case INNODB_CMPMEM_RESET = 'INNODB_CMPMEM_RESET';
    case INNODB_COLUMNS = 'INNODB_COLUMNS';
    case INNODB_DATAFILES = 'INNODB_DATAFILES';
    case INNODB_FIELDS = 'INNODB_FIELDS';
    case INNODB_FOREIGN = 'INNODB_FOREIGN';
    case INNODB_FOREIGN_COLS = 'INNODB_FOREIGN_COLS';
    case INNODB_FT_BEING_DELETED = 'INNODB_FT_BEING_DELETED';
    case INNODB_FT_CONFIG = 'INNODB_FT_CONFIG';
    case INNODB_FT_DEFAULT_STOPWORD = 'INNODB_FT_DEFAULT_STOPWORD';
    case INNODB_FT_DELETED = 'INNODB_FT_DELETED';
    case INNODB_FT_INDEX_CACHE = 'INNODB_FT_INDEX_CACHE';
    case INNODB_FT_INDEX_TABLE = 'INNODB_FT_INDEX_TABLE';
    case INNODB_INDEXES = 'INNODB_INDEXES';
    case INNODB_METRICS = 'INNODB_METRICS';
    case INNODB_SESSION_TEMP_TABLESPACES = 'INNODB_SESSION_TEMP_TABLESPACES';
    case INNODB_TABLES = 'INNODB_TABLES';
    case INNODB_TABLESPACES = 'INNODB_TABLESPACES';
    case INNODB_TABLESPACES_BRIEF = 'INNODB_TABLESPACES_BRIEF';
    case INNODB_TABLESTATS = 'INNODB_TABLESTATS';
    case INNODB_TEMP_TABLE_INFO = 'INNODB_TEMP_TABLE_INFO';
    case INNODB_TRX = 'INNODB_TRX';
    case INNODB_VIRTUAL = 'INNODB_VIRTUAL';
    case KEY_COLUMN_USAGE = 'KEY_COLUMN_USAGE';
    case KEYWORDS = 'KEYWORDS';
    case NDB_TRANSIT_MYSQL_CONNECTION_MAP = 'ndb_transit_mysql_connection_map';
    case OPTIMIZER_TRACE = 'OPTIMIZER_TRACE';
    case PARAMETERS = 'PARAMETERS';
    case PARTITIONS = 'PARTITIONS';
    case PLUGINS = 'PLUGINS';
    case PROCESSLIST = 'PROCESSLIST';
    case PROFILING = 'PROFILING';
    case REFERENTIAL_CONSTRAINTS = 'REFERENTIAL_CONSTRAINTS';
    case RESOURCE_GROUPS = 'RESOURCE_GROUPS';
    case ROLE_COLUMN_GRANTS = 'ROLE_COLUMN_GRANTS';
    case ROLE_ROUTINE_GRANTS = 'ROLE_ROUTINE_GRANTS';
    case ROLE_TABLE_GRANTS = 'ROLE_TABLE_GRANTS';
    case ROUTINES = 'ROUTINES';
    case SCHEMA_PRIVILEGES = 'SCHEMA_PRIVILEGES';
    case SCHEMATA = 'SCHEMATA';
    case ST_GEOMETRY_COLUMNS = 'ST_GEOMETRY_COLUMNS';
    case ST_SPATIAL_REFERENCE_SYSTEMS = 'ST_SPATIAL_REFERENCE_SYSTEMS';
    case ST_UNITS_OF_MEASURE = 'ST_UNITS_OF_MEASURE';
    case STATISTICS = 'STATISTICS';
    case TABLE_CONSTRAINTS = 'TABLE_CONSTRAINTS';
    case TABLE_CONSTRAINTS_EXTENSIONS = 'TABLE_CONSTRAINTS_EXTENSIONS';
    case TABLE_PRIVILEGES = 'TABLE_PRIVILEGES';
    case TABLES = 'TABLES';
    case TABLES_EXTENSIONS = 'TABLES_EXTENSIONS';
    case TABLESPACES = 'TABLESPACES';
    case TABLESPACES_EXTENSIONS = 'TABLESPACES_EXTENSIONS';
    case TRIGGERS = 'TRIGGERS';
    case USER_ATTRIBUTES = 'USER_ATTRIBUTES';
    case USER_PRIVILEGES = 'USER_PRIVILEGES';
    case VIEW_ROUTINE_USAGE = 'VIEW_ROUTINE_USAGE';
    case VIEW_TABLE_USAGE = 'VIEW_TABLE_USAGE';
    case VIEWS = 'VIEWS';
}
